spring.application.name=mascotas-perdidas-med
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=dogfinder;encrypt=true;trustServerCertificate=true
spring.datasource.username=root
spring.datasource.password=1903
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
