spring.application.name=mascotas-perdidas-med
pring.datasource.url=jdbc:postgresql://localhost:5432/mascotas_perdidas
spring.datasource.username=postgres
spring.datasource.password=emmanuelc1903
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

